# Generated by Django 3.1.7 on 2021-03-20 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Naipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naipe', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ritmista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_column='Nome', max_length=200)),
                ('data_entrada', models.DateField(db_column='Data de entrada', verbose_name='Data de entrada')),
                ('data_nascimento', models.DateField(db_column='Data de nascimento', default=None, verbose_name='Data de nascimento')),
                ('cpf', models.CharField(db_column='CPF', default=None, max_length=11, unique=True, verbose_name='CPF')),
                ('telefone', models.CharField(db_column='Telefone', default=None, max_length=11)),
                ('data_saida', models.DateField(blank=True, db_column='Data de saída', null=True, verbose_name='Data de saída')),
                ('curso', models.ForeignKey(db_column='Curso', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='ritmista_app.curso')),
                ('grupo', models.ManyToManyField(db_column='Grupo', default=None, to='ritmista_app.Grupo')),
                ('naipe', models.ForeignKey(db_column='Naipe', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='ritmista_app.naipe')),
            ],
        ),
    ]
